name: interval_skip_list
description: This data structure maps intervals to values and allows you to find all intervals that contain an index in O(ln(n)), where n is the number of intervals stored.
version: 0.0.3
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/interval_skip_list

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
